FROM golang:latest

RUN apt-get update

WORKDIR /app

ENV CGO_ENABLED=0

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o start ./cmd/main.go

EXPOSE 8000
CMD [ "./start", "-env=production"]